from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_IVGA_dialog(object):
    def setupUi(self, IVGA_dialog):
        IVGA_dialog.setObjectName("IVGA_dialog")
        IVGA_dialog.resize(630, 466)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        IVGA_dialog.setFont(font)
        IVGA_dialog.setWindowTitle("Exportación parcelas a GML")
        self.verticalLayout = QtWidgets.QVBoxLayout(IVGA_dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.Logo = QtWidgets.QLabel(IVGA_dialog)
        self.Logo.setMinimumSize(QtCore.QSize(48, 48))
        self.Logo.setMaximumSize(QtCore.QSize(48, 48))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("IVGA.png"))
        self.Logo.setScaledContents(True)
        self.Logo.setObjectName("Logo")
        self.horizontalLayout.addWidget(self.Logo)
        self.label = QtWidgets.QLabel(IVGA_dialog)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.label.setOpenExternalLinks(True)
        self.horizontalLayout.addWidget(self.label)

        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_2 = QtWidgets.QLabel(IVGA_dialog)
        self.label_2.setMinimumSize(QtCore.QSize(116, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.Selec = QtWidgets.QTableWidget(IVGA_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Selec.setFont(font)
        self.Selec.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.Selec.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed|QtWidgets.QAbstractItemView.SelectedClicked)
        self.Selec.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.Selec.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.Selec.setWordWrap(False)
        self.Selec.setObjectName("Selec")
        self.Selec.setColumnCount(6)
        self.Selec.setRowCount(0)
        self.Selec.horizontalHeader().setDefaultSectionSize(20)
        self.Selec.horizontalHeader().setHighlightSections(False)
        self.Selec.horizontalHeader().setMinimumSectionSize(20)
        self.Selec.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.Selec, 0, 1, 1, 1)

        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.verticalLayout.addLayout(self.horizontalLayout_1)
        self.check_lbl = QtWidgets.QLabel(IVGA_dialog)
        self.check_lbl.setMinimumSize(QtCore.QSize(116, 0))
        self.check_lbl.setObjectName("check_lbl")
        self.horizontalLayout_1.addWidget(self.check_lbl)
        self.check = QtWidgets.QCheckBox(IVGA_dialog)
        self.check.setObjectName("check")
        self.horizontalLayout_1.addWidget(self.check)
        self.Validar = QtWidgets.QPushButton(IVGA_dialog)
        self.Validar.setObjectName("Validar")
        self.horizontalLayout_1.addWidget(self.Validar)
        self.options = QtWidgets.QLineEdit(IVGA_dialog)
        self.options.setReadOnly(True)
        self.options.setObjectName("options")
        self.horizontalLayout_1.addWidget(self.options)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.fileName_lbl = QtWidgets.QLabel(IVGA_dialog)
        self.fileName_lbl.setMinimumSize(QtCore.QSize(116, 0))
        self.fileName_lbl.setObjectName("fileName_lbl")
        self.horizontalLayout_2.addWidget(self.fileName_lbl)
        self.fileName = QtWidgets.QLineEdit(IVGA_dialog)
        self.fileName.setObjectName("fileName")
        self.horizontalLayout_2.addWidget(self.fileName)
        
        
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_3 = QtWidgets.QLabel(IVGA_dialog)
        self.label_3.setMinimumSize(QtCore.QSize(116, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.data = QtWidgets.QDateTimeEdit(IVGA_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.data.sizePolicy().hasHeightForWidth())
        self.data.setSizePolicy(sizePolicy)
        self.data.setMinimumSize(QtCore.QSize(157, 25))
        self.data.setMaximumSize(QtCore.QSize(157, 25))
        self.data.setCalendarPopup(True)
        self.data.setObjectName("data")
        self.horizontalLayout_3.addWidget(self.data)
        self.label_5 = QtWidgets.QLabel(IVGA_dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.Inspire3 = QtWidgets.QRadioButton(IVGA_dialog)
        self.Inspire3.setObjectName("Inspire3")
        self.horizontalLayout_3.addWidget(self.Inspire3)
        self.Inspire4 = QtWidgets.QRadioButton(IVGA_dialog)
        self.Inspire4.setObjectName("Inspire4")
        self.horizontalLayout_3.addWidget(self.Inspire4)
        

        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_4 = QtWidgets.QLabel(IVGA_dialog)
        self.label_4.setMinimumSize(QtCore.QSize(116, 0))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.desti = QtWidgets.QLineEdit(IVGA_dialog)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.desti.setFont(font)
        self.desti.setObjectName("desti")
        self.horizontalLayout_4.addWidget(self.desti)
        self.Carpeta = QtWidgets.QPushButton(IVGA_dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Carpeta.sizePolicy().hasHeightForWidth())
        self.Carpeta.setSizePolicy(sizePolicy)
        self.Carpeta.setMinimumSize(QtCore.QSize(33, 29))
        self.Carpeta.setMaximumSize(QtCore.QSize(33, 29))
        self.Carpeta.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Carpeta.setIcon(icon1)
        self.Carpeta.setAutoDefault(False)
        self.Carpeta.setObjectName("Carpeta")
        self.horizontalLayout_4.addWidget(self.Carpeta)

        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.Idioma = QtWidgets.QComboBox(IVGA_dialog)
        self.Idioma.addItems(['Español', 'English'])
        self.horizontalLayout_5.addWidget(self.Idioma)
        self.Crear = QtWidgets.QPushButton(IVGA_dialog)
        self.Crear.setObjectName("Crear")
        self.horizontalLayout_5.addWidget(self.Crear)
        self.Cerrar = QtWidgets.QPushButton(IVGA_dialog)
        self.Cerrar.setObjectName("Cerrar")
        self.horizontalLayout_5.addWidget(self.Cerrar)

        self.retranslateUi()
        self.Cerrar.clicked.connect(IVGA_dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(IVGA_dialog)

    def retranslateUi(self):
        self.label_5.setText("   INSPIRE:")
        self.Inspire3.setText("v3")
        self.Inspire4.setText("v4")
        if self.Idioma.currentIndex() == 0:
            #_translate = QtCore.QCoreApplication.translate
            self.Selec.setHorizontalHeaderLabels(["S", "RefCat", "Conservar", "LocalId", "Area", "Namespace"])
            self.label.setText('<a href="https://www.catastro.minhafp.es/asistente_catreg/img/IVGA.pdf">Exportación parcelas catastrales<br/>(formato INSPIRE GML CP)</a>')
            self.label_2.setText("Parcelas\nseleccionadas")
            self.check_lbl.setText("Validar Ref. Cat.")
            self.Validar.setText("Validar")
            self.fileName_lbl.setText("Nombre del fichero")
            self.label_3.setText("Fecha y hora")
            self.data.setDisplayFormat("dd-MM-yyyy H:mm")
            self.label_4.setText("Carpeta destino")
            self.Crear.setText("Crear GML")
            self.Cerrar.setText("Salir")
            self.msg_noLayer = "No hay ninguna capa activa"
            self.msg_noVector = "La capa activa debe ser de tipo vectorial"
            self.msg_noPolygon = "Debe seleccionar como mínimo una parcela"
            self.msg_noPolygonSelected = "El elemento seleccionado no es de tipo polígono"
            self.msg_noValidCRS = "La capa activa no utiliza un sistema de coordenadas compatible"
            self.msg_noName = "Debe definir el nombre del fichero"
            self.msg_fileExists = "El fichero {}.gml ya existe\n\n¿Desea reemplazarlo?"
            self.msg_done = "Archivo GML creado en la carpeta destino: \n{}.gml"
            self.msg_notFound = "Las Referencias Catastrales siguientes no se encuentran en Catastro:{}"
            self.msg_equalGeometries = "La parcela de Referencia catastral {} no interviene en el proceso"
            self.msg_contourError = "El contorno de las parcelas afectadas no coincide con Catastro.\nEl IVGA solo será positivo condicionado en caso de afección a dominio público"
        else:
            self.Selec.setHorizontalHeaderLabels(["S", "RefCat", "Preserve", "LocalId", "Area", "Namespace"])
            self.label.setText('<a href="https://www.catastro.minhafp.es/asistente_catreg/img/IVGA.pdf">Cadastral Parcel GML Generation\n(INSPIRE GML CP format)</a>')
            self.label_2.setText("Selected parcels")
            self.check_lbl.setText("Check Ref. Cat.")
            self.Validar.setText("Check")
            self.fileName_lbl.setText("File Name")
            self.label_3.setText("TimeStamp")
            self.data.setDisplayFormat("dd-MM-yyyy H:mm")
            self.label_4.setText("Save to folder")
            self.Crear.setText("Generate GML")
            self.Cerrar.setText("Close")
            self.msg_noLayer = "No active layer found"
            self.msg_noVector = "Active layer must be vector type"
            self.msg_noPolygon = "At least one parcel must be selected"
            self.msg_noPolygonSelected = "The selected element is not polygon type"
            self.msg_noValidCRS = "Active layer CRS is invalid"
            self.msg_noName = "Filename must be defined"
            self.msg_fileExists = "{}.gml file already exists\n\n¿Do you want to replace it?"
            self.msg_done = "GML file created in folder: \n{}.gml"
            self.msg_notFound = "The following Cadastral Parcel Refferences have not been found in Cadastre:{}"
            self.msg_equalGeometries = "The Cadastral Parcel with refference {} does not intervene in the process"
            self.msg_contourError = "The contour for the modified Cadastral Parcels does not match the original Cadastral Parcels.\nThe IVGA will only be conditional positive in case of affection od public domain"
           
